### ISSUE TITLE
The site crashed on order tracking, where the junk data is inputted in order ID.

### ISSUE THREAD

**Issue by mudanish** [rak5ha/cricket_dynam#17]
The site crashed on order tracking, where the junk data is inputted in order ID.
![image](https://cloud.githubusercontent.com/assets/17979263/13914528/bef60eae-ef70-11e5-9e23-884d65e7b53b.png)

**Comment by cricketdynamics** [comment]
Please can you fix as this would be critical.

**Comment by rak5ha** [comment]
Fixed.
