### ISSUE TITLE
At the time of checkout, the system is not adding up the delivery amount, although showing it. It should automatically add the amount if the user does not select the delivery option BY DEFAULT.

### ISSUE THREAD

**Issue by mudanish** [rak5ha/cricket_dynam#35]
![image](https://cloud.githubusercontent.com/assets/17979263/13915068/44b101f4-ef74-11e5-862f-a7ec04ebc695.png)
![image](https://cloud.githubusercontent.com/assets/17979263/13915071/45b544de-ef74-11e5-9736-9812936115d7.png)

**Comment by rak5ha** [comment]
Duplicate.
