### ISSUE TITLE
In case of purchasing items where the window ask for specifications, if we keep changing the "knocking" option, the window size kept on increasing - which is abnormal behavior

### ISSUE THREAD

**Issue by mudanish** [rak5ha/cricket_dynam#39]
In case of purchasing items where the window ask for specifications, if we keep changing the "knocking" option, the window size kept on increasing - which is abnormal behavior

**Comment by mudanish** [comment]
Not reproducible

**Comment by rak5ha** [comment]
Closing. We getting rid of the popup anyway.
