### ISSUE TITLE
At the time of selecting items for basket, there is a message appearing "Continue Shopping" or "update Basket" - in presence of this message if I select another item for the basket, the box which enters the order details disappears with that message box. next time it works okay when that dialogue is not there

### ISSUE THREAD

**Issue by mudanish** [rak5ha/cricket_dynam#41]
At the time of selecting items for basket, there is a message appearing "Continue Shopping" or "update Basket" - in presence of this message if I select another item for the basket, the box which enters the order details disappears with that message box. next time it works okay when that dialogue is not there

**Comment by mudanish** [comment]
Not reproducible

**Comment by rak5ha** [comment]
no popup.
