### ISSUE TITLE
On selecting an item for the basket, the system shows its “available quantity” for example 50 in stock.

### ISSUE THREAD

**Issue by mudanish** [rak5ha/cricket_dynam#45]
On selecting an item for the basket, the system shows its “available quantity” for example 50 in stock.

On entering the complete quantity system did not proceed to the basket
On clicking the shown quantity, the system showed distributed quantities without any categorization.

So I entered each quantity separately and zeroed the stock, but system always showed me that 50 are in stock.

![image](https://cloud.githubusercontent.com/assets/17979263/13915342/dd1be35e-ef75-11e5-8f17-f0d2e47c9610.png)

**Comment by mudanish** [comment]
I think this is just refreshing issue as after the transaction system has put Protection on Out of Stock

**Comment by rak5ha** [comment]
Not an issue. Testers are using the stock up. 
Change from coming soon but put to out of stock instead - show the product details but mark as out of stock.

**Comment by mudanish** [comment]
Done
