### ISSUE TITLE
At the time of “Order Review” there is no need to take input of “Delivery method” amount!

### ISSUE THREAD

**Issue by mudanish** [rak5ha/cricket_dynam#46]
![image](https://cloud.githubusercontent.com/assets/17979263/13915400/4e724b9c-ef76-11e5-9a16-11a5c4f75e01.png)

**Comment by mudanish** [comment]
Delivery Method is provided if the user need to change the method at last moment

**Comment by rak5ha** [comment]
I agree with Danish. This needs to be here.
